name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/pnpm
      - name: Build Package
        run: pnpm build
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/pnpm
      - name: Check Package
        run: pnpm check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/pnpm
      - name: Lint Package
        run: pnpm lint
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/pnpm
      - name: Format Package
        run: pnpm format:check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/pnpm
      - name: Test Package
        run: pnpm test
