name: Compressed File Size

on:
  pull_request:

jobs:
  file_size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/pnpm
      - name: Report File Size
        uses: preactjs/compressed-size-action@v2
        with:
          build-script: '--filter stylex-variants build'
          pattern: 'library/dist/*.{js,cjs}'
