name: Publish Package

on:
  release:
    types: [published]

jobs:
  ci:
    uses: LevinUncu/stylex-variants/.github/workflows/ci.yml@main
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/pnpm
      - name: Build Package
        run: pnpm build
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
